export { default as MainContainer } from './MainContainer'
export { default as PageContainer } from './PageContainer'
export { default as StepHeaderContainer } from './StepHeaderContainer'
export { default as StepLogoContainer } from './StepLogoContainer'
export { default as RegContentContainer } from './RegContentContainer'
export { default as RegContainer } from './RegContainer'
export { default as RegFormContainer } from './RegFormContainer'
